language: generic

services:
  - docker

before_install:
  - docker build -t harshagr63/react-test -f ./client/Dockerfile.dev

script:
  - docker run harshagr63/react-test npm test

after_success:
  - docker build -t harshagr63/multi-client ./client
  - docker build -t harshagr63/multi-nginx ./nginx
  - docker build -t harshagr63/multi-server ./server
  - docker build -t harshagr63/multi-worker ./worker

  # login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push images to Docker Hub
  - docker push harshagr63/multi-client
  - docker push harshagr63/multi-nginx
  - docker push harshagr63/multi-server
  - docker push harshagr63/multi-worker


